--- #YAML:1.0
 name: CSS::Declarative
 abstract: Declarative domain for working with CSS.
 version: 0.01
 author:
   - Michael Roberts <michael@vivtek.com>
 license: perl
 distribution_type: module
 requires:
   Decl              0.08
 recommends: -
 build_requires: -
 urls:
   license: http://dev.perl.org/licenses/
 meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
 generated_by: hand!
